spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sh?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: xxxxxxxxxxxxx@qq.com #发送邮件的邮箱地址
    password: xxxxxxxxxx #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: xxxxxxxxx@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  servlet:
    multipart:
      max-request-size: 5GB  # 上传文件总的最大值 默认10MB
      max-file-size: 1GB #单个文件最大值 默认10MB
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  type-aliases-package: org.sacc.SaccHome.mbg.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#showSql
logging:
  level:
    org.sacc.SaccHome.mapper: debug
URL: http://127.0.0.1:8080
server:
  port: 8080
jwt:
  secret: JO6HN3NGIU25G2FIG8V7VD6CK9B6T2Z5
  expire: 60000
