spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sh?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1129126684@qq.com #发送邮件的邮箱地址
    password: qdagjmmhwxrfhaia #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1129126684@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  redis:
    host: 123.56.2.36
    port: 6379
    password: xhn200232
mybatis:
  type-aliases-package: org.sacc.SaccHome.mbg.model
  mapper-locations: classpath:mapper/*.xml
